#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer,molokai,srcery,onedark,jellybeans,palenight,one,nord,hybrid,SpaceVim
    colorscheme="SpaceVim"
    colorscheme_bg="dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "mil"
    statusline_iseparator = "bar"
    # buffer_index_type = 4
    enable_tabline_filetype_icon = true
    # 是否在状态栏上显示当前模式，默认情况下，不显示 Normal/Insert 等
    enable_statusline_mode = true
    automatic_update = true # SpaceVim自动更新
    disabled_plugins = ["clighter", "clighter8"]  # 禁用插件

    # 多的主题，你可以载入 colorscheme 模块
    # colorscheme = "gruvbox"

    # colorscheme = "OceaniwcNext"
    # colorscheme_bg = "dark"

    # colorscheme = "NeoSolarized"
    # colorscheme_bg = "dark"
    # 背景可以取值 "dark" 和 "light"

    # 启用/禁用终端真色，在目前大多数终端下都是支持真色的，当然也有
    # 一小部分终端不支持真色，如果你的 SpaceVim 颜色看上去比较怪异
    # 可以禁用终端真色，将下面的值设为 false
    enable_guicolors = true

    # statusline设置，启用时才有效
    # 设置状态栏上分割符号形状，如果字体安装失败，可以将值设为 "nil" 以
    # 禁用分割符号，默认为箭头 "arrow"
    # statusline_separator = "nil"
    # statusline_separator = "bar"
    # 设置顶部标签列表序号类型，有以下五种类型，分别是 0 - 4
    buffer_index_type = 1
    # 0: 1 ➛ ➊
    # 1: 1 ➛ ➀
    # 2: 1 ➛ ⓵
    # 3: 1 ➛ ¹
    # 4: 1 ➛
    # 显示/隐藏顶部标签栏上文件类型图标，这一图标需要安装 nerd fonts，
    # 如果未能成功安装这一字体，可以隐藏图标
    enable_tabline_filetype_icon = true
    # 是否在状态栏上显示当前模式，默认情况下，不显示 Normal/Insert 等
    # 字样，只以颜色区分当前模式
    enable_statusline_display_mode = true
    # 状态栏左端部分的构成
    statusline_left_sections = ['winnr', 'major mode', 'filename', 'fileformat', 'minor mode lighters', 'version control info', 'search status']
    # 状态栏右端部分的构成
    statusline_right_sections = [
       'battery status',
       'cursorpos',
       'percentage',
       'input method',
       'date',
       'time',
    ]
    # 列表可以由以下一项或多项组成
    # 'winnr' 当前窗口编号
    # 'syntax checking'
    # 'filename' 文件名
    # 'fileformat' 文件格式
    # 'major mode'
    # 'minor mode lighters'
    # 'cursorpos' 光标位置
    # 'percentage' 百分比
    # 'date' 日期
    # 'time' 时间
    # 'whitespace' 打开或者保存文件时，如果第 n 行的行尾有空格则显示 trailing[n]，并不能实时显示出行尾有空格的行号。
    # 'battery status' 电池状态
    # 'input method' 输入法
    # 'search status' 搜索状态
    #######################################################################
    # MY OWN OPTIONS
    filemanager = "defx"
    autocomplete_method = "deoplete"
    #snippet_engine = "ultisnips"
    # 启动函数名称，该函数中可以使用Vim Script
    # 启动函数文件位置：~/.SpaceVim.d/autoload/myspacevim.vim
    # 函数 bootstrap_before 将在读取用户配置后执行，而函数 bootstrap_after 将在 VimEnter autocmd 之后执行。
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    # Vim兼容
    # vimcompatible = true
    # Vim兼容：Normal模式窗口快捷键的前缀改为X，s作为删除字符
    windows_leader = 's'
    # Vim兼容：语言专用的前缀键，f、F、t、T改为搜索
    enable_language_specific_leader = false
    # Vim兼容：智能关闭窗口q改为录制宏
    windows_smartclose = ''

[options]
    guifont = "CaskaydiaCove Nerd Font Mono:style=SemiLight:h11"

[options]
    custom_color_palette = [
        ["#282828", "#a89984", 246, 235],
        ["#a89984", "#504945", 239, 246],
        ["#a89984", "#3c3836", 237, 246],
        ["#665c54", 241],
        ["#282828", "#83a598", 235, 109],
        ["#282828", "#fe8019", 235, 208],
        ["#282828", "#8ec07c", 235, 108],
        ["#282828", "#689d6a", 235, 72],
        ["#282828", "#8f3f71", 235, 132],
    ]

[options]
    # 文件树插件可选值包括：
    # - nerdtree （默认）
    # - vimfiler: 需要编译 vimproc.vim, 在目录 bundle/vimproc.vim 下
    # - defx: 需要 +py3 支持
# 默认的快捷键是F3, SpaceVim 也提供了另外一组快捷键 SPC f t 和 SPC f T 来打开文件树
    filemanager = "defx"
    filetree_direction = "left"

# 默认情况下文件树是打开的，如果需要设置文件树默认关闭，需要修改 enable_vimfiler_welcome 选项。
[options]
    enable_vimfiler_welcome = true

[options]
    filetree_direction = "left"
[options]
    default_indent = 4
    expand_tab = true

[options]
    guifont = "SourceCodePro Nerd Font Mono:h11"
[options]
    enable_guicolors = false
    snippet_engine = "neosnippet"
    statusline_separator = 'arrow'
    sidebar_width = 30
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
[options]
    colorscheme = "NeoSolarized"
    colorscheme_bg = "dark"
# 注意: 为了在 Vim 中使用谷歌 suggestions，需要在 ~/.SpaceVim.d/init.toml 的 [options] 片段中加入如下配置：
[options]
    enable_googlesuggest = true

# 代办事项管理器
[options]
   todo_labels = ['fixme', 'question', 'todo', 'idea']
   todo_prefix = '@'


[options]
    # options for layers checkers
    enable_neomake = true
    enable_ale = false
    lint_on_the_fly = false
    # option for autocomplete
    autocomplete_method = "deoplete"
    # bootstrap configuration
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

# 在自动检测项目根目录时，有时候我们需要忽略掉一些目录，可以表达式前面添加 !， 比如，忽略掉 node_packages/ 文件夹：
[options]
    project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '!node_packages/']
    project_rooter_outermost = false

# ----------------- SpaceVim 添加的各种 layers ---------------------------------
# 强化`/`搜索显示
[[layers]]
    name = "incsearch"

[[layers]]
  name = "core#statusline"

# 计算器, 日历, 书签等小工具
[[layers]]
    name = 'tools'

# 禁用 SpaceVim 的 checkers layer, 让 coc.nvim 来管理
[[layers]]
    name = "checkers"
    enable = false

# 启用 autocomplete 模块，启用模块时，可以列出一些模块选项，并赋值，
# 关于模块的选项，请阅读各个模块的文档
[[layers]]
    name = "autocomplete"
    auto_completion_return_key_behavior = "nil"
    auto_completion_tab_key_behavior = "smart"
    auto_completion_enable_snippets_in_popup = true
    autocomplete_parens = true
    auto_completion_delay = 200
    auto_completion_complete_with_key_sequence = "nil"
    auto_completion_complete_with_key_sequence_delay = 0.1

[[layers]]
  name = "ui"
  enable_scrollbar = true

# 版本控制
[[layers]]
    name = "VersionControl"
    enable-gtm-status = false

[[layers]]
    name = "git"
    git-plugin = "fugitive"

[[layers]]
    name = "fzf"

[[layers]]
    name = "lang#markdown"

[[layers]]
    name = "lang#latex"

[[layers]]
    name = "lang#c"
    enable_clang_syntax_highlight = true

[[layers]]
    name = "lang#python"

[[layers]]
    name = "lang#toml"

[[layers]]
    name = "lang#vim"

[[layers]]
    name = "lang#sh"

[[layers]]
    name = "format"

#Python IDE配置
[[layers]]
    name = "lang#python"

#C/C++ IDE配置#
[[layers]]
    name = "lang#"
    enable_clang_syntax_highlight = true

[[layers]]
  name = "lsp"


[[layers]]
  repo = 'lilydjwg/colorizer'
  on_cmd = ["ColorHighlight", "ColorToggle"]   # 可以通过 :h dein-options 查阅。
  on_func = 'colorizer#ColorToggle'
  merged = false



[[layers]]
  name = "lang#c"
  [layer.clang_std]
    cpp = "c11"

[[custom_plugins]]
    repo = 'lilydjwg/colorizer'
    merged = false

[[custom_plugins]]
    repo = 'joshdick/onedark.vim'
    merged = false

[[custom_plugins]]
name = "Yggdroot/LeaderF"
merged = 0
[[custom_plugins]]
name = "tpope/vim-scriptease"
merged = 0
on_cmd = "Scriptnames"


# 添加自定义插件 junegunn/vader.vim
[[custom_plugins]]
repo = "junegunn/vader.vim"
merged = false


[[custom_plugins]]
name = "mhartington/oceanic-next"
merged = 0

# coc.nvim 核心配置，不要删除
# ~/.cache/vimfiles/repos/github.com/neoclide/coc.nvim
[[custom_plugins]]
name = 'neoclide/coc.nvim'
merge = 0



[[custom_plugins]]
name = 'antoinemadec/coc-fzf'
branch = 'release'

[[custom_plugins]]
name = 'junegunn/fzf.vim'

# 快速搜索文件和 buffer
[[custom_plugins]]
name = "Yggdroot/LeaderF"
build = "./install.sh"

# 快速编辑 markdown 的表格
[[custom_plugins]]
name = 'dhruvasagar/vim-table-mode'

# 更加美观的 tagbar
[[custom_plugins]]
name = 'liuchengxu/vista.vim'

# 更加方便的调节窗口的大小
[[custom_plugins]]
name = 'simeji/winresizer'

# 为 c/cpp 提供基于 lsp 的高亮
[[custom_plugins]]
    name = 'jackguo380/vim-lsp-cxx-highlight'

# 从 http://cplusplus.com/ 和 http://cppreference.com/ 获取文档
[[custom_plugins]]
    name = 'skywind3000/vim-cppman'

# 利用 git blame 显示当前行的 commit message
[[custom_plugins]]
    name = 'rhysd/git-messenger.vim'
    lazy =  1
    on_cmd = 'GitMessenger'

# 以悬浮窗口的形式打开终端
[[custom_plugins]]
    name = 'voldikss/vim-floaterm'
    merged = 0

# 显示搜索的标号
[[custom_plugins]]
    name = 'google/vim-searchindex.git'
    merged = 0

# 记账
[[custom_plugins]]
    name = 'jonsmithers/vim-beancount'
    merged = 0

# 常用snippets
[[custom_plugins]]
    name = 'honza/vim-snippets'
    merged = 0

# 用于高效操作与括号、引号或html、xml标签相关的配对符号(surrounding)
[[custom_plugins]]
    name = 'tpope/vim-repeat'
    merged = 0

# 文本对象
[[custom_plugins]]
    name = 'kana/vim-textobj-user'
    merged = 0

    [[custom_plugins]]
    name = 'kana/vim-textobj-indent'
    merged = 0

    [[custom_plugins]]
    name = 'kana/vim-textobj-syntax'
     merged = 0

[[custom_plugins]]
    name = 'kana/vim-textobj-function'
    merged = 0

[[custom_plugins]]
    name = 'sgur/vim-textobj-parameter'
    merged = 0

# ctags
[[custom_plugins]]
    name = 'ludovicchabant/vim-gutentags'
    merged = 0



#"给当前光标下的单词增加下划线
[[custom_plugins]]
    name = 'itchyny/vim-cursorword'
    merged = 0

#多层括号配色
[[custom_plugins]]
    name = 'luochen1990/rainbow'


[[custom_plugins]]
    name = 'kien/rainbow_parentheses.vim'
    merged = 0

[[custom_plugins]]
    name = 'mechatroner/rainbow_csv'
    merged = 0

# 查找替换
[[custom_plugins]]
    name = 'liuchengxu/vim-clap'
    merged = 0


[[custom_plugins]]
    name = 'nvim-telescope/telescope.nvim'


[[custom_plugins]]
    name = 'Yggdroot/LeaderF'
    merged = 0


#强大的搜索定位，快速移动
[[custom_plugins]]
    name = 'easymotion/vim-easymotion'
    merged = 0

#"快速将括号、‘’、“”、[]等替换
#[[custom_plugins]]
#    name = 'vim-surround'


[[custom_plugins]]
    name = 'gelguy/wilder.nvim'
    merged = 0


[[custom_plugins]]
    name = 'Yggdroot/indentLine'
    merged = 0

[[custom_plugins]]
    name = 'chxuan/change-colorscheme'
    merged = 0


[[custom_plugins]]
    name = 'kyazdani42/nvim-web-devicons'
    merged = 0


[[custom_plugins]]
    name = 'terryma/vim-multiple-cursors'
    merged = 0

# (类名、变量、函数)标签列表插件
[[custom_plugins]]
    name = 'vim-scripts/taglist.vim'
    merged = 0


[[custom_plugins]]
    name = 'majutsushi/tagbar'
    merged = 0

[[custom_plugins]]
    name = 'Shougo/defx.nvim'
    merged = 0



[[custom_plugins]]
    name = 'kristijanhusak/defx-git'
    merged = 0


[[custom_plugins]]
    name = 'kristijanhusak/defx-icons'
    merged = 0



# 目录树插件
[[custom_plugins]]
    name = 'scrooloose/nerdtree'
    merged = 0



# 树形目录-在 NERDTree中显示git信息插件
[[custom_plugins]]
    name = 'Xuyuanp/nerdtree-git-plugin'
    merged = 0


#"taglist的增强版，显示变量函数宏等
[[custom_plugins]]
    name = 'majutsushi/tagbar'
    merged = 0



[[custom_plugins]]
    name = 'jistr/vim-nerdtree-tabs'
    merged = 0

# 书签管理插件
[[custom_plugins]]
    name = "MattesGroeger/vim-bookmarks"
    merged = 0


# 补全插件
[[custom_plugins]]
    name = "Shougo/deoplete.nvim"
    merged = 0
[[custom_plugins]]
    name = "roxma/nvim-yarp"
    merged = 0
[[custom_plugins]]
    name = "roxma/vim-hug-neovim-rpc"
    merged = 0
[[custom_plugins]]
    name = "Valloric/YouCompleteMe"
    merged = 0
[[custom_plugins]]
    name = "SirVer/ultisnips"
    merged = 0
[[custom_plugins]]
    name = "honza/vim-snippets"
    merged = 0


# 格式化代码
[[custom_plugins]]
    name = "tell-k/vim-autopep8"
    merged = 0
[[custom_plugins]]
    name = "sbdchd/neoformat"
    merged = 0
[[custom_plugins]]
    name = ""
    merged = 0



# markdown格式高亮插件
[[custom_plugins]]
name = "suan/vim-instant-markdown"
merged = 0

# 快捷键菜单插件
[[custom_plugins]]
name = "skywind3000/quickmenu.vim"
merged = 0


# git插件 窗口边缘标识git变化
[[custom_plugins]]
name = "airblade/vim-gitgutter"
merged = 0

# git命令封装插件
[[custom_plugins]]
name = "tpope/vim-fugitive"
merged = 0

# 修改与撤销树插件
[[custom_plugins]]
name = "mbbill/undotree"
merged = 0



# 书签管理插件
[[custom_plugins]]
name = "MattesGroeger/vim-bookmarks"
merged = 0


# 同ack一样的文件内容搜索工具插件【需要安装第三方搜索软件】
[[custom_plugins]]
name = "jremmen/vim-ripgrep"
merged = 0

# 模糊搜索fzf
[[custom_plugins]]
name = "junegunn/fzf"
merged = 0

# 模糊搜索fzf
[[custom_plugins]]
name = "junegunn/fzf.vim"
merged = 0

# markdown格式高亮插件
[[custom_plugins]]
name = "suan/vim-instant-markdown"
merged = 0

# 代码注释插件
# [[custom_plugins]]
# name = "preservim/nerdcommenter"
# merged = 0
# SpaceVim 有内置代码注释 <space>+c+l 、<sapce>+c+u <space>+c+L

# vim8.1的终端辅助插件
[[custom_plugins]]
name = "skywind3000/vim-terminal-help"
merged = 0


[[custom_plugins]]
name = "nlknguyen/papercolor-theme"
merged = 0




[[custom_plugins]]
name = "sonph/onehalf"
merged = 0





[[custom_plugins]]
name = "lifepillar/vim-solarized8"
merged = 0





[[custom_plugins]]
name = "altercation/vim-colors-solarized"
merged = 0





[[custom_plugins]]
name = "overcache/NeoSolarized"
merged = 0





[[custom_plugins]]
name = "lifepillar/vim-gruvbox8"
merged = 0





[[custom_plugins]]
name = "wsniper/vim-color-theme-protect-eyes"
merged = 0





[[custom_plugins]]
name = "Rigellute/shades-of-purple.vim"
merged = 0





[[custom_plugins]]
name = "atrnh/magical-girl-vim"
merged = 0





[[custom_plugins]]
name = "bluz71/vim-moonfly-colors"
merged = 0


[[custom_plugins]]
name = "flazz/vim-colorschemes"
merged = 0

[[custom_plugins]]
name = "liuchengxu/space-vim-theme"
merged = 0


[[custom_plugins]]
name = "folke/twilight.nvim"
merged = 0

[[custom_plugins]]
name = "sonph/onehalf"
merged = 0

[[custom_plugins]]
name = "kyoz/purify"
merged = 0


[[custom_plugins]]
name = "nightsense/carbonized"
merged = 0

[[custom_plugins]]
name = "nightsense/stellarized"
merged = 0


[[custom_plugins]]
name = "junegunn/seoul256.vim"
merged = 0


[[custom_plugins]]
name = "ayu-theme/ayu-vim"
merged = 0


[[custom_plugins]]
name = "nightsense/cosmic_latte"
merged = 0


[[custom_plugins]]
name = "romainl/flattened"
merged = 0


[[custom_plugins]]
name = "glepnir/oceanic-material"
merged = 0


[[custom_plugins]]
name = "Rigellute/shades-of-purple.vim"
merged = 0

[[custom_plugins]]
name = "drewtempelmeyer/palenight.vim"
merged = 0


[[custom_plugins]]
name = "evturn/cosmic-barf"
merged = 0


[[custom_plugins]]
name = "lifepillar/vim-gruvbox8"
merged = 0


[[custom_plugins]]
name = "machakann/vim-colorscheme-kemonofriends"
merged = 0


[[custom_plugins]]
name = "stulzer/heroku-colorscheme"
merged = 0


[[custom_plugins]]
name = "vim-scripts/nightshade.vim"
merged = 0


[[custom_plugins]]
name = "bluz71/vim-moonfly-colors"
merged = 0


[[custom_plugins]]
name = "mangeshrex/everblush.vim"
merged = 0


[[custom_plugins]]
name = "bluz71/vim-moonfly-colors"
merged = 0


[[custom_plugins]]
name = "wimstefan/Lightning"
merged = 0


[[custom_plugins]]
name = "wsniper/vim-color-theme-protect-eyes"
merged = 0


[[custom_plugins]]
name = "ghifarit53/tokyonight-vim"
merged = 0


[[custom_plugins]]
name = "vim-scripts/donbass.vim"
merged = 0


[[custom_plugins]]
name = "megantiu/true.vim"
merged = 0


[[custom_plugins]]
name = "raphamorim/lucario"
merged = 0


[[custom_plugins]]
name = "atrnh/magical-girl-vim"
merged = 0


[[custom_plugins]]
name = "atrnh/magical-girl-vim"
merged = 0



[[custom_plugins]]
name = "ghifarit53/tokyonight-vim"
merged = 0



[[custom_plugins]]
name = "tjammer/blandon.vim"
merged = 0



[[custom_plugins]]
name = "schickele/vim-fruchtig"
merged = 0


[[custom_plugins]]
name = "yassinebridi/vim-purpura"
merged = 0


[[custom_plugins]]
name = "nightsense/snow"
merged = 0


[[custom_plugins]]
name = "chriskempson/base16-vim"
merged = 0


[[custom_plugins]]
name = "phanviet/vim-monokai-pro"
merged = 0


[[custom_plugins]]
name = "colepeters/spacemacs-theme.vim"
merged = 0


[[custom_plugins]]
name = "sainnhe/gruvbox-material"
merged = 0


[[custom_plugins]]
name = "nightsense/vimspectr"
merged = 0


[[custom_plugins]]
name = "crusoexia/vim-monokai"
merged = 0


[[custom_plugins]]
name = "jnurmine/Zenburn"
merged = 0


[[custom_plugins]]
name = "kristijanhusak/vim-hybrid-material"
merged = 0


[[custom_plugins]]
name = "mhartington/oceanic-next"
merged = 0


[[custom_plugins]]
name = "Rigellute/rigel"
merged = 0


[[custom_plugins]]
name = "rakr/vim-one"
merged = 0



[[custom_plugins]]
name = "wadackel/vim-dogrun"
merged = 0




[[custom_plugins]]
name = "john2x/flatui.vim"
merged = 0




[[custom_plugins]]
name = "kjssad/quantum.vim"
merged = 0




[[custom_plugins]]
name = "protesilaos/prot16-vim"
merged = 0




[[custom_plugins]]
name = "tamlok/detorte"
merged = 0




[[custom_plugins]]
name = "rakr/vim-colors-rakr"
merged = 0




[[custom_plugins]]
name = "romgrk/github-light.vim"
merged = 0

[[custom_plugins]]
name = "ashfinal/vim-colors-paper"
merged = 0



[[custom_plugins]]
name = "machakann/vim-colorscheme-tatami"
merged = 0



[[custom_plugins]]
name = "machakann/vim-colorscheme-snowtrek"
merged = 0



[[custom_plugins]]
name = "lorry-lee/vim-ayumi"
merged = 0




[[custom_plugins]]
name = "severij/vadelma"
merged = 0



[[custom_plugins]]
name = "whzup/greent.vim"
merged = 0



[[custom_plugins]]
name = "stulzer/mitormk-laser"
merged = 0



[[custom_plugins]]
name = "rktjmp/lush.nvim"
merged = 0



[[custom_plugins]]
name = "alaric/nortia.nvim"
merged = 0

[[custom_plugins]]
name = "rafamadriz/neon"
merged = 0


[[custom_plugins]]
name = "shaunsingh/moonlight.nvim"
merged = 0


[[custom_plugins]]
name = "Iron-E/nvim-highlite"
merged = 0



# 窗口管理
# 常用的窗口管理快捷键有一个统一的前缀，默认的前缀 [Window] 是按键 s，可以在配置文件中通过修改 SpaceVim 选项 window_leader 的值来设为其它按键：
#
# [options]
    # windows_leader = "s"
# 快捷键	功能描述
# q	智能关闭当前窗口
# [Window] v	水平分屏
# [Window] V	水平分屏，并编辑上一个文件
# [Window] g	垂直分屏
# [Window] G	垂直分屏，并编辑上一个文件
# [Window] t	新建新的标签页
# [Window] o	关闭其他窗口
# [Window] x	关闭当前缓冲区，并保留新的空白缓冲区
# [Window] q	关闭当前缓冲区
# [Window] Q	关闭当前窗口
# Shift-<Tab>	切换至前一窗口
# 常规模式下的按键 q 被用来快速关闭窗口，其原生的功能可以使用 <Leader> q r 来代替。
#
# 常用编辑器窗口
# 按键	功能描述
# <F2>	打开、关闭语法树
# <F3>	打开、关闭文件树
# Ctrl-<Down>	切换至下方窗口
# Ctrl-<Up>	切换至上方窗口
# Ctrl-<Left>	切换至左边窗口
# Ctrl-<Right>	切换至右边窗口
# 窗口操作常用快捷键
# 每一个窗口都有一个编号，该编号显示在状态栏的最前端，可通过 SPC 编号 进行快速窗口跳转。
#
# 快捷键	功能描述
# SPC 1	跳至窗口 1
# SPC 2	跳至窗口 2
# SPC 3	跳至窗口 3
# SPC 4	跳至窗口 4
# SPC 5	跳至窗口 5
# SPC 6	跳至窗口 6
# SPC 7	跳至窗口 7
# SPC 8	跳至窗口 8
# SPC 9	跳至窗口 9






